---
- hosts: LOCALHOST
  tasks:
   - expect:
      timeout: 30
      command: aws configure
      responses:
         'AWS Access Key ID': "None\n"
         'AWS Secret Access Key': "None\n"
         'Default region name': "None\n"
         'Default output format': "None\n"
