---
- hosts: LOCALHOST
  tasks:
   - expect:
      timeout: 30
      command: aws configure
      responses:
         'AWS Access Key ID': "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}\n"
         'AWS Secret Access Key': "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}\n"
         'Default region name': "{{ lookup('env', 'AWS_REGION') }}\n"
         'Default output format': "json\n"
