# Site settings
title: sl-iot-ref-arch1
baseurl: "/sl-iot-ref-arch1" 
repository: https://github.com/SolaceLabs/sl-iot-ref-arch1



#----------------------------------------------------
# Generally don't modify items below this point

url: "SolaceLabs.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
