# Site settings
title: Solace Testing in AWS
baseurl: "/Solace_testing_in_AWS" 
repository: https://github.com/SolaceLabs/Solace_testing_in_AWS



#----------------------------------------------------
# Generally don't modify items below this point

url: "SolaceLabs.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
